erDiagram
    USUARIO {
        int pk_usuario PK "Chave primária"
        string email_usuario "E-mail do usuário"
        string senha_usuario "Senha hash"
        boolean eh_adm_usuario "Indica se é administrador"
    }
